-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 30-11-2023 a las 14:34:55
-- Versión del servidor: 10.4.28-MariaDB
-- Versión de PHP: 8.0.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `almacen`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `itemventa`
--

CREATE TABLE `itemventa` (
  `id` int(11) NOT NULL,
  `id_producto` int(11) DEFAULT NULL,
  `cantidad` int(11) DEFAULT NULL,
  `precio` decimal(10,2) DEFAULT NULL,
  `venta_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

--
-- Volcado de datos para la tabla `itemventa`
--

INSERT INTO `itemventa` (`id`, `id_producto`, `cantidad`, `precio`, `venta_id`) VALUES
(1, 3, 1, 122999.00, 1),
(2, 3, 1, 122999.00, 2);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `productos`
--

CREATE TABLE `productos` (
  `codigo` int(10) NOT NULL,
  `categoria` varchar(255) NOT NULL,
  `fechaAlta` date NOT NULL DEFAULT current_timestamp(),
  `nombre` varchar(255) NOT NULL,
  `cantidad` int(11) NOT NULL,
  `descripcion` text NOT NULL,
  `precio` decimal(11,2) NOT NULL,
  `imagen` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

--
-- Volcado de datos para la tabla `productos`
--

INSERT INTO `productos` (`codigo`, `categoria`, `fechaAlta`, `nombre`, `cantidad`, `descripcion`, `precio`, `imagen`) VALUES
(1, 'Celulares', '2023-10-12', 'Celular Samsung Galaxy A04e 32GB Black', 15, 'El Galaxy A04e posee un procesador Octa-Core, 3G de RAM y 32GB de almacenamiento interno. Además, podrás expandir la capacidad con una tarjeta MicroSD de hasta 1TB. Podrás utilizar el Samsung Galaxy A04e durante horas, gracias a su batería de 5000 mAh de capacidad.\r\n\r\nSu camara principal de 13MP te ayudará a realizar tomas increíbles todos los días, mientras que la de 2MP ajustará la profundidad de campo, logrando fotografías de gran calidad. Te permitirá disfrutar de tus series, películas y juegos favoritos. Con 6,4 pulgadas y resolución HD+ (720 x 1600) podrás ver todas las cosas que te gustan en gran calidad de imagen.\r\nAguante el profe Ignacio!', 80000.00, 'productos/a04.png'),
(2, 'Celulares', '2023-10-12', 'Celular Motorola G72 128GB Azul', 18, 'Obtendrás toda la potencia que necesitas para jugar, reproducir videos y usar las funciones de la cámara gracias al potente procesador octa core Mediatek Helio G99 y la memoria RAM de 6GB. También cuenta con un almacenamiento de 128GB (112GB disponibles) y la posibilidad de expandirlo con una tarjeta MicroSD de hasta 1TB. Su batería de 5000 mAh lograrás usar el Moto G72 por más tiempo con una sola carga. Sacá fotos nítidas con poca luz, tomas espectaculares ultra gran angular, retratos profesionales y acercamientos muy detallados. El sensor de 108 MP permite sacar fotos nítidas con cualquier luz. Además, suma un gran angular de 8MP y una macro de 2MP.\r\n\r\nCuenta con NFC: Coloca el teléfono cerca de una terminal NFC para comprar o recargar otras tarjetas. Es rápido, seguro y evita que lleves dinero en efectivo.\r\n', 180000.00, 'productos/193206-800-auto.png'),
(3, 'Celulares', '2023-10-12', 'Celular Samsung Galaxy A14 128GB Black', 19, 'Diseño con marcos redondeados, botones laterales, triple cámara trasera alineada y un acabado elegante en color negro intenso, el diseño del Galaxy A14 se convierte en el centro de atención. Con 5000 mAh de capacidad, podrás utilizar tu smartphone durante todo el día. Captura cada recuerdo con la triple cámara trasera de 50, 5 y 2 megapíxeles. La cámara principal captura paisajes magníficos, la de profundidad agrega dimensiones impresionantes y la macro obtiene detalles finos. Aprovecha para sacarte las mejores selfies con la cámara frontal de 13mp. Samsung Galaxy A14 ofrece una pantalla de 6,6 pulgadas con resolución FHD+. Cuenta con un almacenamiento interno de 128GB y 4GB de RAM para que puedas guardar todos tus archivos y aplicaciones, y utilices el Galaxy A14 con fluidez. Incluso podrás sumar una tarjeta MicroSD de hasta 1TB.', 122999.00, 'productos/samsung a14.png'),
(4, 'Celulares', '2023-10-12', 'Celular Samsung Galaxy A33 5G 128GB Black', 4, 'El celular Samsung Galaxy A33 5G, en su color “Awesome Black” con acabado mate, brinda un estilo moderno y elegante que destaca del resto. Con su sensor de huellas dactilares incorporado en la pantalla, podrás iniciar sesión instantáneamente en tus aplicaciones y sitios web. Cuenta con una batería de 5000 mAh recargable con cable USB C, capaz de brindar la energía necesaria para que transmitas, compartas contenido, juegues y disfrutes de tu Galaxy A33 durante todo el día. Logra fotos más nítidas y claras con la cámara OIS de 48 MP, amplia tu ángulo de visión con la cámara ultra ancha de 8 MP, personaliza el enfoque con la cámara de profundidad de 2 MP y acércate a los detalles con la cámara macro de 5 MP.', 141999.00, 'productos/A33-SAMSUNG-1.png'),
(5, 'Celulares', '2023-10-12', 'Celular Samsung Galaxy A24 128GB Negro', 7, 'Disfruta el diseño del celular Samsung Galaxy A24. Triple cámara, botones laterales y curvas elegantes. Un gran estilo minimalista en color negro. Combina la potencia de su procesador Octa-core con los 128 GB de almacenamiento y los 6 GB de RAM para un rendimiento rápido y eficiente.  Batería La batería de 5000 mAh te permitirá continuar con lo que estés haciendo, durante horas y horas. Captura momentos memorables con detalles nítidos gracias a la cámara principal de 50 MP, ajusta la profundidad de campo en tus fotos con la cámara de profundidad de 5 MP y obtén detalles finos con la cámara de 2 MP. Además, con la frontal de 13 MP, tendrás increíbles selfies en donde vos serás el centro de atención.', 171999.00, 'productos/Samsung_Galaxy_A24_Black_5bc7ec5d9d.png'),
(6, 'Celulares', '2023-10-26', 'Celular Samsung Galaxy S20 FE 5G 128GB Azul', 7, 'El celular Samsung Galaxy S20 FE se convertirá en el complemento perfecto gracias a su clasificación IP68 que le otorga resistencia al agua y al polvo, este smartphone soporta hasta 1,5 metros de agua durante 30 minutos, por lo que no tendrás que preocuparte si se moja un poco y querés seguir jugando o sacando fotos. Con una batería de 4500mAh, el smartphone tiene la energía que requiere para durar todo el día, y es lo suficientemente inteligente como para ahorrarla en los momentos que más la necesitas. Ofrece tres cámaras con lentes de nivel profesional: podrás encuadrar la escena con la gran angular (12 MP), ampliarla con la Ultra Wide (12 MP) o acercarla con el zoom óptico de 3x de la cámara de teleobjetivo (8 MP). Además, con la cámara frontal de 32 MP, tus selfies y stories alcanzarán un nivel completamente nuevo, capturando muchos más detalles para convertirte en la estrella de cada toma. Con su procesador Octa-Core y los 6 GB de RAM, lograrás cambiar de una aplicación a otra sin trabas, tener transmisiones en vivo claras y jugar hasta la victoria, aprovechando al máximo la velocidad. Con el almacenamiento interno de 128 GB y la capacidad de almacenar hasta 1 TB más con una tarjeta microSD, el único límite para todo lo que podés almacenar lo ponés vos.', 318000.00, 'productos/S20_FE.png'),
(7, 'Celulares', '2023-10-26', 'Celular Samsung Galaxy A34 5G 128GB', 8, 'Samsung Galaxy A34 se convierte en el centro de atención. Ofrece una batería de 5000 mAh. Además, si necesitas revivir tu Galaxy rápidamente, cuenta con carga rápida de hasta 25W. Captura cada recuerdo con la triple cámara trasera de 48, 8 y 5 megapíxeles, el Galaxy A34 ofrece una pantalla de 6,6 pulgadas con resolución FHD+ y 120Hz de tasa de refresco. Cuenta con un almacenamiento interno de 128GB y 6GB de RAM para que puedas guardar todos tus archivos y aplicaciones, y utilices el Galaxy A34 con fluidez. Incluso podrás sumar una tarjeta MicroSD de hasta 1TB.', 227000.00, 'productos/a34.png'),
(8, 'Celulares', '2023-10-26', 'Celular Samsung Z Flip4 128 GB', 1, 'El celular Samsung Z Flip4 posee un tamaño compacto.\r\nPosee un procesador de 4nm mejorado que trabaja con la batería de larga duración de 3700 mAh (uso típico) para funcionar hora tras hora. Ofrece cámaras ancha y ultra ancha de 12 MP, además de una delantera de 10 MP con la función de autorretrato. El smartphone está diseñado para ser duradero ya que soporta hasta 200.000 pliegues y promete ser el dispositivo plegable de Samsung más resistente ya que cuenta con el exclusivo Corning Gorilla Glass Victus+.', 519600.00, 'productos/Galaxy_Z_Flip4.png'),
(9, 'Celulares', '2023-10-26', 'Celular Motorola G32 6GB 128GB Plata', 14, 'Disfruta de tu teléfono con una sola carga, gracias a su potente batería de 5000 mAh que te permite trabajar y jugar por más tiempo. Haz que tus seres queridos salgan siempre bien. El sensor de 50 MP permite sacar fotos nítidas con cualquier luz. La pantalla de 6.5\" es amplia, y cómoda para la mano. Con la resolución Full HD+, tus fotos y videos siempre se verán super nítidos. ', 150000.00, 'productos/frente_1_5.png'),
(10, 'Celulares', '2023-10-31', 'Celular Motorola G13 4GB 128GB', 6, 'Disfruta de tu teléfono con una sola carga La increíble batería de 5000 mAh te permite escuchar tus listas de reproducción durante más tiempo, realizar videollamadas extensas con tus amigos y ver tus series favoritas hasta el final.\r\n\r\nCon un sistema de cámaras de 50 MP y tecnología Quad Pixel, el Moto G13 saca fotos nítidas en condiciones de poca luz, acercamientos detallados y mucho más. Cuenta con una cámara Macro que te acerca más al objetivo para que descubras los detalles que no se pueden ver con un lente convencional. Además, con la cámara frontal de 8MP saca selfies perfectas para las redes y publica tu mejor versión.\r\n\r\nLa pantalla HD+ de 6.5\" está diseñada sin bordes para que puedas disfrutar de la imagen completa y ver todos los detalles. Con la velocidad de actualización de 90 Hz3 de la pantalla, puedes cambiar de aplicaciones, jugar y mirar sitios web de forma rápida y fluida.', 109000.00, 'productos/MOTO-G13-1.1-.png'),
(11, 'Celulares', '2023-10-31', 'Celular Motorola Edge 40 Pro 256GB Celeste Glaciar', 8, 'Déjate cautivar por el diseño curvo, elegante y sin bordes del celular Motorola Edge 40 Pro, el cuál te brindará una comodidad excepcional. Su parte posterior presenta un increíble sistema de triple cámara y una estructura mate que ofrece una sensación suave como la seda. Este teléfono posee protección contra el polvo, la suciedad, la arena e incluso contra un chapuzón en el agua, ya que cuenta con clasificación IP68. Captura detalles impresionantes en cualquier condición de luz con la cámara principal de 50 MP, amplia el encuadre de tus fotos con la gran angular y de profundidad de 50 MP y observa el mundo de cerca con la macro de 12 MP. Con la cámara delantera lograrás tomarte selfies increíbles, ya que ofrece 60 MP. Su avanzado procesador Qualcomm Snapdragon 8 Gen 2 te permitirá aprovechar al máximo tu celular, ofreciendo un desempeño rápido y eficiente. Además, debido a su conexión 5G, podrás divertirte con tus videojuegos favoritos, descargar contenido y transmitir sin inconvenientes y a una velocidad increíble. Disfruta de una pantalla sin bordes, súper rápida y con mil millones de tonos de colores. Con 6,67 pulgadas y resolución FHD+, verás todo tu contenido favorito, como series, películas y videos, en una calidad de imagen increíble. ', 549000.00, 'productos/CelesteGlaciar.png'),
(12, 'Celulares', '2023-10-31', 'Celular Motorola Razr 40 Ultra 512GB Negro Infinito', 4, 'Captura tus momentos gracias a su cámara principal de 12 MP lograrás fotos brillantes, retratos profesionales y acercamientos detallados. También podrás disfrutar de tus selfies con su cámara frontal de 32 MP. Además, cuenta con la tecnología Quad Pixel que ofrece una sensibilidad 4 veces mayor en ambientes con poca luz para tomar imágenes nítidas y reales. Con su potente procesador Snapdragon 8+ vas a tener mucha más velocidad y, además, verás un mejor desempeño junto a su memoria interna de 512 GB y RAM de 12 GB, que te brindarán todo el espacio y la rapidez que necesitas en tu día a día. Posee un moderno diseño en distintos colores. Cuenta con una pantalla externa pOLED súper amplia de 3.6” con la cual podrás seguir usando el teléfono mientras está cerrado. Por otro lado, ofrece una pantalla interna flexible de 6.9” y bisagra “gota” sin espacios entre sus lados, esta pantalla es FHD+ pOLED con 165Hz, inmersiva con sonido ecualizado por Dolby Atmos. Con su batería de 3800 mAh lograrás trabajar y jugar durante el día y la noche con una sola carga. Por otro lado, vas a poder cargar de forma rápida con el cargador TurboPower de 33 W o disfrutar la libertad que te brinda la carga inalámbrica.', 700000.00, 'productos/Motorola_Razr_40.png'),
(13, 'Celulares', '2023-10-31', 'Celular Xiaomi Redmi Note 11 128GB Azul', 8, 'El Xiaomi Redmi Note 11 posee un diseño elegante, atractivo y moderno. Cuenta con una pantalla de 6,43 pulgadas, con la que podrás ampliar tu visión y mirar todo lo que te estabas perdiendo. Combina la potencia de su procesador Snapdragon 680 con la memoria RAM de 4GB para obtener un rendimiento más rápido y eficiente. Posee almacenamiento interno de 64GB. Posee una batería de 5000 mAh para que disfrutes durante todo el día. Gracias a su sistema de cámaras (50 MB + 8 MB + 2 MB + 2 MB) lograrás llevar tus fotografías y recuerdos a otro nivel, con perspectivas, colores y detalles excelentes. Además, la cámara selfie cuenta con 13 MP para tomar vídeos nítidos, selfies o videollamadas.', 133000.00, 'productos/redmi-note-11.png'),
(14, 'Celulares', '2023-10-31', 'Xiaomi Redmi 12C 4GB RAM 128GB ROM Lavender Purple', 5, 'Xiaomi Redmi 12C 4GB RAM 128GB ROM\r\nPotente Procesador MediaTek Helio G85 | Pantalla inmersiva de 6,71\" | Cámara dual IA de 50MP.  Procesador MediaTek Helio G85 ofrece un rendimiento más equilibrado y eclipsa a sus pares, mientras que la GPU para juegos Mali-G52 le ofrece una experiencia de entretenimiento fluida. Gran pantalla HD+ de 6,71\"\r\nExperiencia de visualización inmersiva Redmi 12C cuenta con una gran pantalla HD+ de 6,71\", ¡una combinación poco común en su clase! Ya sea que estés jugando o navegando, la pantalla más grande te permite ver más, brindando una experiencia visual más sorprendente e inmersiva para mirar videos. Batería de larga duración de 5000 mAh\r\nEl diseño texturizado elegante y distintivo ofrece un mejor agarre antideslizante, mientras que la carcasa unibody con parte posterior curvada lo hace más cómodo de sostener. El sensor de huellas dactilares está especialmente diseñado para quedar oculto en la isla de la cámara.', 127000.00, 'productos/REDMI12C.png'),
(15, 'Celulares', '2023-10-31', 'Celular Xiaomi Redmi 10 4GB 128GB', 7, 'Almacenamiento: 128 GB RAM: 4 GB LPDDR4X + eMMC\r\n\r\nDimensiones: Altura: 161,95 mm Ancho: 75,53 mm Espesor: 8,92 mm Peso: 181g\r\n\r\nMonitor: Pantalla de puntos FHD + de 6,5 ″\r\n\r\nFrecuencia de actualización: 90 Hz\r\n\r\nAdaptiveSync: 45/60/90 Hz 2400 × 1080, 405 ppp\r\n\r\nModo de lectura 3.0\r\n\r\nCorning Gorilla Glass 3\r\n\r\n', 338799.00, 'productos/REDMI10.png'),
(16, 'Celulares', '2023-10-31', 'Celular Xiaomi Poco F3 6GB 128GB Negro Sin Cargador', 3, 'VIENE SIN CARGADOR. Almacenamiento y RAM: 6GB+128GB Almacenamiento y RAM LPDDR5 + almacenamiento UFS 3.1. Dimensiones: Altura: 163,7 mm Ancho: 76,4 mm Espesor: 7,8 mm Peso: 196g. \r\nPantalla de puntos AMOLED de 6,67 2400x1080 FHD+. Relación de aspecto: 20:9. Relación de contraste: 5.000.000:1. Brillo: 900nits (tipo HBM), 1300nits (pico) HDR10+. Frecuencia de actualización: 120Hz. Tasa de muestreo táctil: 360Hz', 598000.00, 'productos/image7.png'),
(17, 'Celulares', '2023-10-31', 'Celular TCL 40SE 128GB Twilight Purple', 8, 'La potente batería de 5010 mAh y la carga rápida permite un entretenimiento ininterrumpido. Alimentado por Smart Manager, podes escuchar tus canciones favoritas, hacer llamadas sin tener que arrastrar el cargador a todas partes y aprende tus rutinas de cargado para una mejor duración de la vida útil de la batería. Su cámara triple AI de 50MP inspira al máximo tu creatividad. No dejes que la luz te limite, y saca todas las imágenes que quieras, ya que pueden ser capturadas claramente por la cámara triple AI de 50MP de alto píxel. No te pierdas ningún detalle gracias a la cámara macro y destaca elementos y personas con su cámara de profundidad. Además, con la cámara selfie de 8MP ahora puedes sacar selfies de forma automática mientras te relajas y sonreís, sin necesidad de apretar botones. La amplia pantalla de 6,75” con una relación de aspecto de 20:9 brinda una excelente experiencia inmersiva de visualización cinematográfica con la tecnología de NXTVISION. Los diferentes modos de cuidado ocular brindan una experiencia de comodidad en cualquier momento.', 90000.00, 'productos/tcl_40.png'),
(18, 'Celulares', '2023-10-31', 'Celular TCL 403 32GB Prime Black', 29, 'Posee una batería de 3000 mAh con la función Smart Saving, que regula la batería y resguarda un 20% de la misma mientras el teléfono se encuentra sin uso. El TCL 403 cuenta con una cámara principal de 8MP con función macro dentro de la misma, además de la mejora de HDR. Su cámara frontal es de 5MP y posee funciones Flash LCD y Face Beauty. Cuenta con el sistema operativo Android 12 (Go edition), lo que permite utilizar versiones más livianas de todas las aplicaciones y un almacenamiento de 32GB, que se puede complementar con una tarjeta de memoria SD de hasta 512GB.', 50000.00, 'productos/tlc40.png'),
(19, 'Celulares', '2023-10-31', 'Celular ZTE Blade V40 Design 128GB Black', 7, 'La batería de 4500 mAh te ofrecerá una gran duración de carga. De esta forma, podrás utilizar el ZTE Blade V40 Design para jugar juegos, ver videos o utilizar tus redes sociales durante todo el día. La triple cámara trasera de 50, 2 y 2 megapíxeles brinda una gran versatilidad fotográfica y permite capturar imágenes más nítidas y detalladas. Además, con la cámara frontal de 8mp podrás sacarte las mejores selfies para subir a tus redes sociales. La pantalla de 6,6 pulgadas y definición FHD+ te proporcionará colores brillantes y una calidad excepcional mientras disfrutas de tu contenido multimedia, como videos, redes sociales y juegos. Cuenta con memoria RAM de 6GB y una ROM de 128GB, lo que te proporcionará gran capacidad de almacenamiento y la posibilidad de ejecutar varias aplicaciones y tareas al mismo tiempo, sin ralentizar el smartphone.', 94000.00, 'productos/ZTE.png'),
(20, 'Celulares', '2023-10-31', 'Celular Smartphone Alcatel 1 Ultra 1gb 32gb 8mpx Android 11', 7, 'CELULAR SMARTPHONE DE 5 PULGADAS ALCATEL 1 ULTRA ANDROID 11 GO 5033MP-FAOFAR11 • RENDIMIENTO FLUIDO Disfruta de una experiencia más rápida y liviana con la tecnología de Android 11 (edición Go), y obtén un rendimiento mejorado con Smart Manager. • DISEÑO COMPACTO Y ELEGANTE Con su pantalla de 5 pulgadas y bisel curvo para un agarre cómodo, además de la textura finamente tallada antideslizante y antihuellas, tiene un aspecto atractivo con un efecto en movimiento. - Sistema operativo: Android 11 (Go Edition) - Memoria RAM: 1 GB - Almacenamiento: 32 GB (expandible por microSD hasta 32 GB) - Procesador: MediaTek MT6739 1.28 GHz - Pantalla: IPS 5.0 pulgadas HD (480 x 960 px) 16:9 - Cámaras: -- Principal: 8 MPx con HDR y flash LED -- Frontal: 2 MPx con flash LCD - Funciones de cámara: -- Video 1080p @30fps -- Foto panorámica -- Filtros y ajustes automáticos -- Face Beauty - Ranura SIM: Individual NanoSIM 4FF - Conectividad: -- Redes 2G / 3G / 4G LTE -- WiFi 802.11n -- Bluetooth 4.0 -- GPS (A-GPS) - Batería: Iones de litio de 2000 mAh - Dimensiones: 137,6 x 65,7 mm - Peso: 134 gramos - Accesorios incluidos: -- Funda antigolpes -- Auriculares 3.5 mm -- Cable USB de carga -- Cargador USB -- Manual de usuario', 57000.00, 'productos/alcatel.png'),
(21, 'Celulares', '2023-10-31', 'iPhone 13', 2, 'iPhone 13. El sistema de dos cámaras más avanzado en un iPhone. El superrápido chip A15 Bionic. Un gran\r\nsalto en duración de batería. Un diseño resistente. Y una pantalla Super Retina XDR más brillante. Pantalla Super Retina XDR de 6.1 pulgadas.(1) Modo Cine con baja profundidad de campo y cambios de enfoque automáticos en tus videos. Sistema avanzado de dos cámaras de 12 MP (gran angular y ultra gran angular) con Estilos Fotográficos, HDR Inteligente 4, modo Noche y grabación de video 4K HDR en Dolby Vision. Cámara frontal TrueDepth de 12 MP con modo Noche y grabación de video 4K HDR en Dolby Vision. Diseño resistente con Ceramic Shield. Resistencia al agua IP68, líder en la industria.(3)\r\niOS 15 con nuevas funcionalidades para aprovechar tu iPhone al máximo.(4) Compatibilidad con accesorios MagSafe, que se acoplan fácilmente a tu iPhone y permiten una carga inalámbrica más rápida.(5)', 2430000.00, 'productos/iphone.png'),
(22, 'Celulares', '2023-10-31', 'Smartphone Motorola Moto E22 4gb Ram 64gb Negro', 5, 'El moto e22 está diseñado para que te sumerjas en el sonido multidimensional de los parlantes estéreo con Dolby Atmos®. Además, la pantalla fluida de 90 Hz le da vida a tu contenido de entretenimiento. Disfrutá del increíble diseño de primer nivel, el sistema de cámaras de 16 MP y el lector de huella digital, que también funciona como atajo a tus aplicaciones favoritas. Además, aprovechá los 64 GB de almacenamiento. Disfrutá la vida con el moto e22. Pantalla HD+ de 6.5” y 90 Hz + parlantes estéreo con sonido Dolby Atmos® Mirá tu contenido en una pantalla ultra wide y disfrutá el sonido multidimensional que te permite sentir mejor los bajos, descubrir voces más nítidas y escuchar con mayor claridad. Sistema de cámaras de 16 MP con IA. Enfoca al instante y saca fotos de aspecto profesional gracias a las increíbles funciones de cámara con su Inteligencia Artificial. Android 12 + 32 GB de almacenamiento Experiementa la respuesta instantánea del teléfono gracias a su procesador con HyperEngine y Android8 12 full version. Además, podés agregar hasta 1 TB adicional con una tarjeta microSD Diseño sofisticado de primer nivel Disfruta del diseño delgado y elegante a la vez de sentir un producto liviano en tu mano. Lector de huella digital lateral con control táctil. Desbloquea tu teléfono al instante con un simple toque del lector ó tócalo dos veces para acceder a tus aplicaciones favoritas. Características: Procesador: Mediatek Helio G37 Sistema Operativo: Android 12 Sensores: Acelerómetro, Sensor de Proximidad, Brújula (Campo magnético), Huella Dactilar, Desbloqueo Facial Almacenamiento: 32GB Cámara Trasera: Principal: 16 MP (80°) F2.2 Macro: 2MP (80.1°) F2.4 Cámara Frontal: 5 MP Bluetooth: BT 5.0 Dimensiones: 163.56 x 74.65 x 7.99 Peso: 174g', 167000.00, 'productos/e22_Quartz-Black_01--1-.png'),
(23, 'Celulares', '2023-10-31', 'Celular Tecno Pova 4 Azul', 8, 'Celular. Pantalla de 6.82\" HD (720x1640) + pantalla dot-in, tasa de refresco 90Hz. Procesador Helio G99 octa core. Almacenamiento de 256 GB ROM. Memoria RAM de 8 GB. Cámara trasera de 50 MP con Dual Flash / Cámara frontal de 8 MP con One Flash. Conexiones: Wifi. Bluetooth. NFC. Conector 3.5. Lector de tarjetas. Radio FM. GPS. Sistema operativo android 12. Batería de 6000 mAh. Incluye: Cable USB, llave SIM, auriculares y funda de TPU.', 146800.00, 'productos/1CTEC1783.png'),
(24, 'Celulares', '2023-10-31', 'Celular Tecno Spark Go 2023 Negro', 8, 'Celular. Pantalla de 6.6\" HD (720x1612) + pantalla dot-in, tasa de refresco 90Hz. Procesador Mediatek Helio A22 Quad Core de 4 x 2 Ghz. Almacenamiento de 64 GB ROM. Memoria RAM de 4 GB. Cámara trasera de 13 MP / Cámara frontal de 5 MP. Conexiones: Wifi 2.4. Bluetooth 5.0. Lector de tarjetas. Radio FM. GPS. Sistema operativo android 12. Batería de 5000 mAh. Incluye: Cable USB, llave SIM y funda de TPU.', 64800.00, 'productos/0147610_celular-tecno-spark-go-2023_550.png'),
(25, 'Celulares', '2023-10-31', 'Celular Samsung Fold 5 SM-F946B ICY BLUE', 3, 'CELULAR SAMSUNG GALAXY FOLD 5 256GB 12GB RAM BLUE - SM-F946BLBLARO La potencia de una PC, ahora, en tu bolsillo. Conoce el smartphone con una gran pantalla, como un cine móvil. La que es tanto una consola de juegos emocionante como una herramienta multipantalla y multitarea. Y se completa con una potente cámara de calidad profesional. Todo plegado en tus manos. Lo último en pantalla principal de 7,6 Pulgadas Desplega una pantalla impresionante e inmersiva, rediseñada para ofrecerte juegos como nunca antes, visualización cinematográfica dondequiera que estés y productividad estilo PC, todo en un dispositivo del tamaño de una tablet. Nuestro Galaxy Z Fold más liviano y compacto Las leyes de la física no tienen nada en este diseño nivelado. El Galaxy Z Fold5 hace honor a su nombre al plegarse para cerrar, lo que hace que una pantalla enorme quepa en tu bolsillo desafiando a toda lógica. Más delgado, ligero y portátil que nunca Logramos reducir la forma para un agarre más firme de lo que te gusta sin sacrificar nada de potencia Crea el ambiente con tu color favorito ', 1182000.00, 'productos/zfold-phantom-fold-front_5.png'),
(26, 'Celulares', '2023-10-31', 'Celular Motorola Edge 30 Fusion XT2243-1 Blanco Opalo', 7, 'Celular. Pantalla de 6.55\" (20:9). Tecnología pOLED. Resolución 1080 x 2400, FHD+, 402, HiD, 144 Hz. Tipo de vidrio de pantalla Glass 3D. Procesador Qualcomm Snapdragon 888+, Octa Core (hasta 2.84GHz). Capacidad 256 Gb / RAM 12 Gb. Cámara principal: 50MP (84.01) F1.88, Gran angular y profundidad: 13MP (120) F2.2, Macro: 2MP (86.1) F2.4. Zoom digital (8x picture / 8x video). Flash LED. Resolución de video 8K UHD. Cámara frontal 32MP (73.24) F2.2. Flash frontal backlight. Resolución de video 4K UHD. Conexiones: Wi Fi 802.11 a/b/g/n/ac/ax /k/v/r/u - WiFi 6E (2.4, 5 y 6 GHz). Bluetooth 5.2. NFC. HDMI Display port 1.4. GPS, AGPS, GLONASS, Galileo. Redes 5G. USB-C 3.1. Sistema operativo Android 12. Batería de 4400 mAh. Carga turbo. Sensores: Acelerómetro, de proximidad, brújula (campo magnético), Giroscopio, Huella dactilar (bajo dislplay), luz ambiente y desbloqueo facial. Incluye: Herramienta de extracción de SIM, cable de datos USB-C - USB-C, cargador 68W USB-C y funda.', 350000.00, 'productos/91paun0022ar_1_.png'),
(27, 'Notebooks', '2023-11-29', 'Notebook Lenovo LG5 15.6\" Ryzen 7 8GB 512GB SSD 82JW00Q2AR', 4, 'La notebook Lenovo LG5 82JW00Q2AR posee una pantalla FHD de 15,6 pulgadas capaz de ofrecer imágenes y videos impresionantes. Con puertos USB 2.0, 3.2 y HDMI siempre estarás preparado para cualquier situación, pudiendo conectar el dispositivo que quieras a la notebook. Además, cuenta con conexión inalámbrica mediante Bluetooth y Wi-Fi. Su procesador AMD Ryzen 7 5800Hy su memoria de 8GB se complementan para ofrecer un mayor rendimiento con un bajo consumo de energía. Además, los 512GB SSD le dan una gran capacidad de almacenamiento de datos y te permite guardar una mayor cantidad de contenido multimedia. Este modelo posee una batería de 60 Wh para que puedas utilizarla durante el día.', 1299999.00, 'productos/88GMY501582-gallery.webp'),
(28, 'Notebooks', '2023-11-29', 'Notebook ASUS Vivobook 15 15,6\" Intel Core i3 8GB 256GB SSD X1502ZA-EJ830W', 7, 'Combinando su procesador Intel Core i3 con la memoria RAM de 8GB y el almacenamiento SSD de 256GB, la Vivobook 15 ofrece un gran desempeño y podrás tener una excelente experiencia de uso con una gran velocidad. Con una pantalla de 15.6 pulgadas y su resolución FHD, podrás usar la notebook Asus para trabajar o estudiar con comodidad. Además, ofrece tecnología Anti-glare que evita que se produzcan reflejos, por lo que tus ojos no tendrán que esforzarse de más. Con su batería de 42WHrs, 3S1P, 3-cell Li-ion podrás llevar tu Vivobook 15 con vos a todos lados y mantener tu productividad al máximo.', 660000.00, 'productos/AsusVivobook.png'),
(29, 'Notebooks', '2023-11-29', 'Notebook Lenovo IdeaPad 1 15,6” AMD Ryzen 7 16GB 512GB SSD 82R4009BAR', 4, 'La notebook Lenovo IdeaPad 1 posee una pantalla de 15,6 pulgadas con resolución Full HD (1920 x 1080p) capaz de brindar una claridad de color precisa para una fidelidad completa en todo tu contenido favorito. Cuenta con puertos USB, HDMI y conexión inalámbrica mediante Wi-Fi y Bluetooth. Así, estarás preparado para conectar o conectarte con cualquier dispositivo. Su procesador AMD Ryzen 7, junto con su memoria RAM de 16GB y su disco SSD de 512GB, logran ofrecer el almacenamiento que necesitas y un rendimiento óptimo.', 1230000.00, 'productos/LenovoIdeaPad.png'),
(30, 'Notebooks', '2023-11-29', 'X-View Notebook Novabook V6 N3350 Win10 128gb /6gb Ram Intel', 10, 'Windows 10® | Memoria interna 128GB, Slot SSD M.2 SATA interno | Ancho: 332mm, Alto: 224mm, Espesor: 22,3mm | Cámara: 0.3 MP | Procesador: CPU Intel Apollo N3350 (Máx. 2.4GHz), \r\nGPU Intel HD Graphics 500 (650MHz) | Audio: Alto-Parlante, Salida Auricular, Entrada mini HDMI | Memoria: RAM: 6GB DDR3 | Pantalla 14.1\" HD IPS, Resolución: 1366x768px | Batería: Recargable 4000 mAH 7.6V Lithium | Conectividad: Wi-Fi: 802.11 b/g/n, Tecnología Bluetooth®: 4.0, Puerto Ethernet, 2USB / 2.0 y 3.0 | Accesorios incluidos: Cargador\r\n', 299999.00, 'productos/novabook-perspectiva.png'),
(31, 'Notebooks', '2023-11-29', 'MSI CYBORG 15,6\" I7 16 GB 512 GB - BLACK', 4, 'MSI Cyborg (A13VE-218US) 15,6″” FHD GAMING LAPTOP BLACK | Processor: 13th Gen Intel® Core™ i7-13620H , Memory:16GB DDR5 5200MHz RAM, Storage: 512GB NVMe Solid | State Drive, Display: 15.6″” IPS FHD (1920 x 1080) 144Hz Display, Intel® Wi-Fi 6 (2×2/160) Gig+ Bluetooth® 5.2, | Blue Keyboard with Anti-Ghost Key | Video Card: NVIDIA® GeForce RTX™ 4050 Graphics, 6GB | Windows 11 Home x 64 bits, pre instalado | Peso 3,02Kg, Integrated 720p HD Webcam with Dual Digital Microphone Array', 1699999.00, 'productos/MSI.png'),
(32, 'Notebooks', '2023-11-29', 'Notebook Acer Nitro 5 Shale Negro Win 11 Rtx 3050ti I7 11800', 10, 'La notebook Acer Win Nitro 5 es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Su pantalla LED de 15.6\" y 1920x1080 px de resolución te brindará colores más vivos y definidos. Tus películas y series preferidas cobrarán vida, ya que ganarán calidad y definición en cada detalle. Su procesador Intel Core i7 de 8 núcleos, está pensado para quienes buscan la máxima exigencia en la productividad. Está destinado a personas que trabajan con programas de diseño, de edición o tienen un nivel de juego alto. Llevará a cabo varios procesos de forma simultánea, sin frenos y te brindará una experiencia excepcional. El disco sólido de 512 GB hace que el equipo funcione a gran velocidad y por lo tanto te brinda mayor agilidad para operar con diversos programas. Su placa de video NVIDIA GeForce RTX 3050 Ti convierte a este dispositivo en una gran herramienta de trabajo para cualquier profesional del diseño. Te permitirá lograr una gran performance en todos tus juegos y en otras tareas cotidianas que impliquen procesamiento gráfico.', 1360000.00, 'productos/Acer.png'),
(33, 'Notebooks', '2023-11-29', 'MacBook Pro 14\" Apple M1 Pro chip 10-core CPU 16-core GPU - 1TB SSD - Space Grey', 3, 'MacBook Pro 14\" Apple M1 Pro chip 10-core CPU 16-core GPU - 1TB SSD - Space Grey Marca: Apple Modelo: Macbook Pro 14\" Color: Space Grey Capacidad del disco rígido: 1TB Capacidad del SSD: 1TB Resolución de la pantalla: 3024 x 1964 a 254pix Marca del procesador: M1 PRO Línea del procesador: Pro Modelo del procesador: Chip M1 PRO Frecuencia de actualización de la pantalla: 50Hz a 60Hz Nombre del sistema operativo: macOS Edición del sistema operativo: Monterey Con pantalla táctil: No Cantidad de núcleos: 10 Tipo de batería: Polímero de litio Tamaño de la pantalla: 14\" Origen: China', 6442714.00, 'productos/mac.png'),
(34, 'Notebooks', '2023-11-29', 'MacBook Air 13\" M1 Chip 8-core CPU 7-core GPU 256GB Silver', 4, 'Frecuencia de actualización de la pantalla: 60 Hz | Resolución de la pantalla: 2560 px x 1600 px | Con pantalla táctil: No | Tamaño de la pantalla: 13.3 \" | Relación de aspecto: 16:10 | Tipo de resolución de la pantalla: Full HD | Gama de colores: P3 | Con pantalla retina: Sí | Batería: Tipo de batería: Polímero de litio, Duración de la batería: 18 h | Marca: Apple | Línea: MacBook Air | Modelo: A2337 | Capacidad del SSD: 256 GB | Tarjeta gráfica: Apple GPU | Marca del procesador: Apple | Línea del procesador: M1 | Modelo del procesador: M1 | Cantidad de núcleos: 8 | Velocidad máxima del procesador: 3.1 GHz | Nombre del sistema operativo: macOS | Versión del sistema operativo: 10.14 | Edición del sistema operativo: Big Sur | Con Wi-Fi: Sí |  Memoria RAM: 8 GB | Tipo de memoria RAM: DDR3 | Memoria de video: 4 GB | Peso: 1.29 kg.', 2528429.00, 'productos/macAir.webp'),
(35, 'Notebooks', '2023-11-29', 'Notebook Gamer Lenovo Legion 5 Pro 16 Intel Core i7 16GB 512GB SSD RTX 3050 Ti', 4, 'Notebook Gamer Lenovo Legion 5i Pro 16\" 6ta Generación Modelo: 82JF007YAR Color: Storm Grey (gris oscuro) REGALO POR TIEMPO LIMITADO: Xbox Game Pass por 3 meses Juega a más de 100 juegos de gran calidad gracias a Game Pass, que viene incluido Juega más de 100 juegos de gran calidad con tu nuevo portátil Lenovo Legion y tres meses de Xbox Game Pass, EA Play incluido. Se añaden nuevos juegos constantemente, así que siempre tendrás algo nuevo para jugar. Descarga y juega con total fidelidad o juega a juegos de consola desde la nube con el controlador conectado. Con Intel®, sí jugás Jugar nunca volverá a ser lo mismo después de experimentar los procesadores Intel® Core ™ de la 11.ª generación serie H. Reproduce y transmite los últimos títulos AAA en su máxima expresión con velocidades de reloj de hasta 4.60 GHz en varios núcleos, frecuencia de reloj mejorada, 45 vatios de potencia de procesamiento dedicada, hasta 8 núcleos y 16 MB de Intel® Smart Cache. Crea y juega como nunca antes gracias a la tarjeta gráfica Intel® Iris® Xe y tecnologías inteligentes como Intel® Thermal Velocity Boost (TVB), Intel® Dynamic Tuning e Intel®Adaptix™ Tecnologies, que han sido mejoradas para optimizar el rendimiento del sistema. Experimenta velocidades WiFi ultrarrápidas y conexiones fiables con Intel® WiFi 6, WiFi casi 3 veces más rápido con Intel® WiFi 6, incluso en redes con muchos dispositivos conectados. Y gracias a Thunderbolt™ 4**, disfruta de una conexión rápida a través de único solo cable a la alimentación, a los monitores, el almacenamiento y otros tantos millones de dispositivos. Máximo rendimiento para jugadores y creadores Disfruta del máximo rendimiento con las últimas GPU para portátiles NVIDIA® GeForce RTX™ serie 30 para jugadores y creadores. Nuestro diseño fino y ligero, potenciado gracias a los Ray Tracing Cores, Tensor Cores y multiprocesadores de transmisión, ofrece los gráficos de trazado de rayos más realistas, nuevas funciones de vanguardia y el poder de la inteligencia artificial. Mejora tu campo de visión Mejora tu calidad de visión más allá de los videojuegos FHD con la primera pantalla para juegos WQXGA (2560 x 1600) de 16\" del mundo, compatible con NVIDIA® G-Sync y con un 34 % más de densidad de píxeles Dolby Vision™ y VESA DisplayHDR™ soporte 400 con 100 % de precisión de color sRGB y más de 500 nits de brillo máximo. Ponte muy por delante del resto gracias a la tecnología OverDrive, con frecuencias de actualización de hasta 165 Hz y tiempos de respuesta de 3 minutos.', 2461999.00, 'productos/Legion-5-Pro-16ITH6_hero-01.png'),
(36, 'Notebooks', '2023-11-29', 'Notebook Samsung 14\" Intel Core i5 12 núcleos 512GB 16GB Galaxy Book3 Pro NP940XFG-KA1A', 4, 'Cuenta con un diseño tan delgado y un peso de menos de 1,2 kg que es ideal para llevar en tu mochila a donde quieras. Su memoria de 16 GB LPDDR, 512 GB de almacenamiento SSD te brindarán una gran eficiencia y velocidad para disfrutar de una experiencia mucho más rápida. Además, el procesador Intel Core i5, ofrece un rendimiento rápido y confiable para una alta productividad y múltiples tareas. La notebook Samsung Galaxy Book3 Pro cuenta con una pantalla de 14 pulgadas y resolución de 2880x1800, con la que podrás ver todo tu contenido con una gran calidad. La notebook cuenta con un puerto HDM, uno USB 3.2 Y 2 Thunderbolt 4I. Además, con su tecnología inalámbrica, podrás conectarte a cualquier dispositivo mediante WiFi y Bluetooth. Gracias a la batería de larga duración de 54 Wh, que ofrece hasta 16 horas de autonomía, podrás usar la notebook durante todo el día sin tener que preocuparte.', 1399999.00, 'productos/Notebook_Galaxy_Book3_Pro_360_i7_Graphite_PL_664dc19c5a.webp'),
(37, 'Tablets', '2023-11-29', 'Tablet Amazon Fire Hd 8 12gen 2022 Rosa 2 Gb Ram 32 Gb Almacenamiento', 15, 'Modelo: Fire HD 8 (12.ª generación) |Peso: Envase 490g - Producto 355g | Sensores: Acelerómetro, sensores de luz ambiental | Cámara: Frontal e Trasera de 2 MP | Procesador de la cpu: Hexa Core de 2.0GHz | Memoria RAM interna de: 32GB/2GB - Ranura para *tarjeta microSD, hasta 1TB (*no incluida). | Batería Recargable interna: 12 horas de duración de la batería, 5 horas de carga. | Pulgadas: 8\" | Resolución: 1280 x 800 píxeles, relación de aspecto de 16 10 (densidad de ~189 ppp). | Conexiones: USB tipo C - Audio de 3,5 mm. | Sistema Operacional: cuatro sistemas operativos. | Bluetooth: 5.2 | Wifi: 802.11ac de doble banda | Tela: Pantalla táctil capacitiva LCD IPS', 93989.00, 'productos/tabletspecthumb_firehd8_2022.png'),
(38, 'Tablets', '2023-11-29', 'Tablet Lenovo Yt13 Smart K606f 13 8gb 128gb (za8e0024ar)', 4, 'La tablet para entretenimiento en casa Intensifica tu experiencia multimedia Resolución de pantalla 2K con Dolby Vision™ Sonido Dolby Atmos® envolvente a través de cuatro altavoces JBL Perfecta para videojuegos con procesamiento Qualcomm Adreno 650 Sumérgete en la historia Ponla de pie, cuelga e inclina tu tablet con un soporte de acero inoxidable, mientras sientes el drama y la tensión de tus películas y programas favoritos con una impresionante calidad de imagen 2K a través de Dolby Vision ™. Disfrutarás de la paleta de colores sRGB completa durante muchas horas con protección ocular con certificación TÜV que elimina los niveles dañinos de luz azul. Audio cinematográfico en movimiento Experimenta y escucha cada nota y efecto de audio en su propio espacio físico a través del audio cinematográfico en movimiento de Dolby Atmos® con cuatro altavoces JBL. Podrás gozar de cada himno de concierto, pódcast y videollamada mientras disfrutas de la sintonización precisa del audio de primera calidad de Lenovo. Juegos más exigentes Juega los títulos más exigentes desde el punto de vista gráfico desde el sillón o la cama con una plataforma móvil diseñada para videojuegos de alta resistencia. O aprovecha toda la gloria con baja latencia en los últimos títulos triple A con videojuegos en la nube. Además, jugarás todo el día con una batería de larga duración, que se recarga en poco tiempo. Trabaja con dos pantallas. Desde cualquier lugar. Obtén una mayor productividad con doble pantalla. El práctico puerto micro-HDMI transforma tu tablet en una segunda pantalla rápida y sencilla de 2K para tu laptop si quisieras (laptop no incluida). Y el Lenovo Precision Pen 2 opcional (no incluido) es un regalo del cielo para los creadores, ya que te ofrece la destreza y la libertad para dibujar diseños directamente en la pantalla, tal y como lo harías en un bloc de dibujo. Procesador Hasta Qualcomm® Snapdragon™ 870, ocho núcleos, hasta 3,2 GHz Sistema operativo Android™ 11 Tarjeta gráfica GPU Qualcomm® Adreno 650', 1292899.00, 'productos/LenovoYoga.webp'),
(39, 'Tablets', '2023-11-29', 'iPad 10.2\" Wi-Fi 64GB (9na Gen) - Space gray', 8, 'El nuevo iPad viene con una espectacular pantalla Retina de 10.2 pulgadas, el potente chip A13 Bionic y una cámara frontal ultra gran angular con Encuadre Centrado. Además, es compatible con el Apple Pencil y el Smart Keyboard.(1)\r\nCon el iPad, harás de todo como si nada. Y por menos de lo que imaginas.', 699990.00, 'productos/iPad-9na-generacion-64-GB.png'),
(40, 'Tablets', '2023-11-29', 'Tablet Lenovo Tab P12 Pro ZA9D0075AR Teclado + Pen + Case', 5, 'Con un diseño delgado y ligero, la Lenovo Tab P12 Pro se convertirá en la mejor compañera para tus momentos de trabajo o entretenimiento. Junto con su funda, teclado y pen podrás mantener tu productividad al máximo y llevarla con vos a donde sea. | Pantalla:  te brindará colores excelentes con su pantalla OLED de 12,6 pulgadas y resolución de 2560 x 1600 p. Además, con Dolby Atmos y el sistema superior de cuatro altavoces JBL, experimentarás graves intensificados y una fidelidad de audio mejorada. Así, disfrutarás de ver videos, series y más, en una gran calidad de imagen y sonido.  | Rendimiento: Posee el procesador Qualcomm 870, una memoria de 256 GB y una batería de 10000 mAh para que puedas realizar tus tareas con facilidad, guardar todos tus archivos e imágenes y utilizarla durante todo el día sin que nada te detenga. | Cámara: Su doble cámara trasera posee 5 MP FF + 13 MP AF, mientras que su cámara frontal ofrece 8 MP FF. | puertos: 1 USB Type-C 3.1 (Gen 2), 1 microSD™ Card Slot', 900000.00, 'productos/tab-p12-pro.webp'),
(41, 'Tablets', '2023-11-29', 'Tablet Lenovo M10 ZAAE0066AR', 15, 'La Tablet Lenovo cuenta con 64GB de memoria interna para que la personalices cómo y cuándo quieras, lleves tus aplicaciones favoritas, guardes tus libros, fotos y música. Cuenta con un puerto USB-2.0, mientras que gracias a su placa de red de Wi-Fi vas a poder conectarte inalámbricamente a internet. Este producto cuenta con cámara principal de 8 megapíxeles mediante la cual podrás capturar tus imágenes y con la cámara frontal de 5 megapíxeles, vas a poder realizar videollamadas o sacarte fotos instantáneas de manera sencilla. La Tablet Lenovo ZAAE0066AR cuenta con un diseño compacto y moderno. Dispone de una pantalla de 10,1\" FHD con una resolución de 1920x1200.', 179999.00, 'productos/lenovo-tablet-m10-hero-1-.webp'),
(42, 'Tablets', '2023-11-29', 'Tablet Lenovo Yoga 11 128GB 4GB ZA8W0010', 10, 'Cuenta con un puerto USB-2.0, mientras que gracias a su placa de red de Wi-Fi vas a poder conectarte inalámbricamente a internet. | Este producto cuenta con cámara principal de 8 megapíxeles mediante la cual podrás capturar tus imágenes y con la cámara frontal de 8 megapíxeles, vas a poder realizar video llamadas o sacarte fotos instantáneas de manera sencilla. | La Tablet Lenovo ZA8W0010 cuenta con un diseño compacto y moderno. Dispone de una pantalla de 11\" 2K con una resolución de 2000x1200. | La Tablet Lenovo cuenta con 128GB de memoria interna para que la personalices cómo y cuándo quieras, lleves tus aplicaciones favoritas, guardes tus libros, fotos y música. | Tablet 4 GM RAM', 320000.00, 'productos/TabletLenovo.webp'),
(43, 'Tablets', '2023-11-29', 'Tablet EXO Wave 10\" 4GB ram 64GB WiFi Dual i101 T2', 15, 'Procesador : Tiger T310 Quad Core hasta 2.0 GHz | GPU PowerVR GE8300 | Pantalla : 10,1\" HD (1280x800) IPS HD multi-touch 10 puntos\" | Memoria : 4 GB DDR | Almacenamiento : 64 GB eMMC | Lector de Tarjetas SD | Software : Android 12 GMS | Wi-Fi : Wi-Fi DUAL BAND Wireless 802.11 a/b/g/n - 4G LTE | Bluetooh 5.0 ; Radio FM - GPS | Sonido : Parlante integrado | Webcam : FRONTAL 2MP / TRASERA 5MP con flash | Accesorios : 1 x Type-C USB / 1 x Auricular y/o Microfono 3,5mm,5mm\r\n', 330000.00, 'productos/tablet_01.webp'),
(44, 'Tablets', '2023-11-29', 'iPad Pro 11\"Chip M1 Wi-Fi + Cellular 5G 256GB (3era Gen) Silver', 2, 'iPad Pro 11\" Wi-Fi + Celular 5G 256GB M1 chip (3era Gen) | Marca:Apple Línea: iPad Pro | Modelo: 3ª Generación | Capacidad: 256 GB | Tamaño de la pantalla: 11 \" | Con conexión celular: Sí | Nombre del sistema operativo: iPadOS | Versión del sistema operativo: 14 | Conectividad: Bluetooth, Wi-Fi, MIMO | Cantidad de cámaras traseras: 2', 2671286.00, 'productos/ipad-pro-11-select-wifi-silver-202104_GEO_IN.png'),
(45, 'Notebooks', '2023-11-29', 'Notebook Lenovo 14” Core i3 8GB 256GB SSD IdeaPad Slim 3 82XA001KAR', 10, 'La notebook Lenovo IdeaPad Slim 3 está equipada con una pantalla de 14 pulgadas con resolución FHD (1920x1080). Esta ofrece imágenes nítidas y detalles claros para una experiencia visual satisfactoria. Su característica Anti-glare ayuda a reducir los reflejos y el deslumbramiento, lo que permite utilizar la notebook en diversas condiciones de iluminación sin molestias visuales. Está equipada con Bluetooth 5.1 para conectividad inalámbrica. También cuenta con un lector de tarjetas, puertos HDMI y USB, y conector 3.5 mm. Por otro lado, la notebook viene con una cámara HD 720p que incluye Privacy Shutter para proteger la privacidad del usuario. Su procesador es un Intel Core i3, que cuenta con 8 núcleos y 8 hilos. Tiene una frecuencia base de 1.8 GHz y puede alcanzar una frecuencia turbo de hasta 3.8 GHz, lo que lo hace adecuado para tareas diarias y multitarea eficiente. Con 6 MB de caché, este procesador garantiza un rendimiento ágil y una respuesta rápida en aplicaciones y sistemas operativos. Incorpora una batería integrada con una capacidad de 47Wh, lo que proporciona una duración adecuada para el uso diario. Cuenta con un almacenamiento SSD de 256 GB. Este tipo de almacenamiento ofrece velocidades de lectura y escritura rápidas y contribuye a un rendimiento ágil en general. Además, tiene 8 GB de memoria, lo que permite una multitarea fluida y un rendimiento ágil en aplicaciones y tareas diarias.', 640000.00, 'productos/lenovocore.webp'),
(46, 'Notebooks', '2023-11-30', 'Notebook Dell Inspiron 15,6” Intel i5 8GB 256GB SSD VPYJY', 5, 'Combinando su procesador Intel Core i5 con la memoria RAM de 8GB y el almacenamiento SSD de 256GB, la Inspiron 3520 ofrece un desempeño ágil en las tareas diarias, una experiencia de uso rápida y el espacio necesario para todos tus archivos. La notebook posee una pantalla de 15,6 pulgadas y resolución FHD con bisel súper delgado, que maximizará tu área de visualización para que disfrutes de todas tus películas, series y videos favoritos en una gran calidad de imagen. La Inspiron 3520 cuenta con puertos USB, HDMI y conector para auriculares. Además, gracias a su tecnología Bluetooth podrás conectarte con dispositivos externos de forma inalámbrica. Posee una batería de 41Wh, para que la puedas utilizar durante todo el día y mantener tu productividad al máximo.', 969000.00, 'productos/notebookdell.webp'),
(47, 'Notebooks', '2023-11-30', 'Notebook Lenovo Legion 5 6ta Gen AMD Ryzen 5 16GB 512GB', 4, 'Notebook Lenovo Legion 5 6ta Gen AMD Ryzen 5 16GB 512GB Modelo: 82NW006SAR Color: Blanco Rendimiento gamer definitivo. Autonomía de la batería excepcional. Puedes disfrutar de un rendimiento para gaming de elite en una laptop delgada y liviana con una duración de la batería increíble gracias a los nuevos procesadores móviles hasta AMD Ryzen™ 7. Procesador: Procesador AMD Ryzen™ 5 5600H (3,30 GHz hasta 4,20 GHz) | Sistema operativo: Windows 11 Home | Single Language 64 | Pantalla: 15,6\" WQHD (2560 x 1440), IPS, antirreflectante, sin capacidad táctil, 100 % sRGB, 300 nits, 165 Hz, retroiluminación | LED Memoria: 8 GB DDR4-3200MHz (SODIMM) + 8 GB DDR4-3200MHz (SODIMM) | Almacenamiento: 512 GB SSD M.2 2242 PCIe TLC | ', 1563999.00, 'productos/NotebookLenovoLegion5.webp'),
(48, 'Notebooks', '2023-11-30', 'Notebook Lenovo IdeaPad 1 14” Intel Celeron 4GB 128GB SSD 82V60027AR', 10, 'La notebook Lenovo IdeaPad 1 posee una pantalla de 14 pulgadas con resolución HD (1366x768) capaz de brindar una claridad de color precisa para una fidelidad completa en todos tu contenido favorito. Su procesador Intel Celeron, junto con su memoria RAM de 4GB y su disco SSD de 128GB, logran ofrecer el almacenamiento que necesitás y un rendimiento de juego. La IdeaPad 1 cuenta con puertos USB, HDMI y conexión inalámbrica mediante Wi-Fi y Bluetooth. Así, estarás preparado para conectar o conectarte con cualquier dispositivo.', 450000.00, 'productos/Lenovo-12512.webp'),
(49, 'Notebooks', '2023-11-30', 'Notebook Acer Aspire 5 Slim - Ryzen 3 - 4gb - 128gb - 15.6\" - Win 10 S', 10, 'Modelo: A515-43-R19L | Procesador: AMD Ryzen 3 3200u Dual-core processor 3.5GHz | Sistema operativo: Windows 10 S Inglés | Display y gráficos : AMD Radeon Vega 3 mobile Graphics | Tamaño de pantalla: 15,6 \" / LCD / IPS - FHD | Tecnología de retroiluminación: LED | Resolución de la pantalla: 1920 x 1080 | Memoria: 4 GB - DDR4 SDRAM | Almacenamiento: SSD 128 GB | Red de comunicación: LAN inalámbrica estándar IEEE 802.11 ac | ', 731228.00, 'productos/2-e1581071819932.webp'),
(50, 'Notebooks', '2023-11-30', 'Notebook Lenovo 14\" Core I5 8GB RAM 256GB T14', 5, 'NOTEBOOK LENOVO  T14 I5 8G 256 14 W LENOVO Detalles Especificaciones Técnicas - Adaptador de corriente:65W USB-C (2-pin) - Almacenamiento:256GB SSD M.2 2280 PCIe x4 NVMe Opal2 - Batería:Integrated 50Wh - Calibrador de color:No - Cámara:720p with Privacy Shutter - Chip de seguridad:Discrete TPM 2.0 - Chipset:Intel SoC Platform - Color de la caja:Negro - Ethernet:100/1000M - Garantía básica:3 años On-site - Gestión del sistema:No - Gráficos:Integrated Intel Iris Xe Graphics functions as UHD Graphics - Lector de huellas dactilares:Touch Style, Match-on-Chip - Lector de tarjetas:MicroSD Card Reader - Marca:LENOVO - Material de la Caja:PPS / 50% GF (Top), PC + ABS / Talc15 + Magnesium Alloy (Keyboard Cover), PA / 50% GF (Bottom) - Memoria:8GB Soldada DDR4 3200 - Micrófono:2x, Array - Monitor:14\" FHD (1920x1080) IPS 300nits Anti-glare - NFC:No - Óptico:No - Pantalla táctil:No - Procesador:Intel Core i5-1135G7 (4C / 8T, 2.4 / 4.2GHz, 8MB) - Sistema operativo:Windows 10 Pro 64, Spanish - Teclado:Non-backlit, Spanish (LA) - Tratamiento de superficies:Not Anti-microbial - WLAN + Bluetooth:Intel AX201 11ax, 2x2 + BT5.2 - WWAN:No', 1763955.00, 'productos/20W1S0E200-3.png'),
(51, 'Celulares', '2023-11-30', 'Celular Motorola Razr 40 Ultra 512GB Negro Infinito', 10, 'Gracias a su cámara principal de 12 MP lograrás fotos brillantes, retratos profesionales y acercamientos detallados. También podrás disfrutar de tus selfies con su cámara frontal de 32 MP. Además, cuenta con la tecnología Quad Pixel que ofrece una sensibilidad 4 veces mayor en ambientes con poca luz para tomar imágenes nítidas y reales. Con su potente procesador Snapdragon 8+ vas a tener mucha más velocidad y, además, verás un mejor desempeño junto a su memoria interna de 512 GB y RAM de 12 GB, que te brindarán todo el espacio y la rapidez que necesitás en tu día a día. El celular Motorola Razr 40 Ultra posee un moderno diseño en distintos colores. Cuenta con una pantalla externa pOLED súper amplia de 3.6” con la cual podrás seguir usando el teléfono mientras está cerrado. Por otro lado, ofrece una pantalla interna flexible de 6.9” y bisagra “gota” sin espacios entre sus lados, esta pantalla es FHD+ pOLED con 165Hz, inmersiva con sonido ecualizado por Dolby Atmos. Con su batería de 3800 mAh lograrás trabajar y jugar durante el día y la noche con una sola carga. Por otro lado, vas a poder cargar de forma rápida con el cargador TurboPower de 33 W o disfrutar la libertad que te brinda la carga inalámbrica.', 900860.00, 'productos/Motorola_Razr_40_Ultra_Negro_Infinito2_62fe2e0883.png');
INSERT INTO `productos` (`codigo`, `categoria`, `fechaAlta`, `nombre`, `cantidad`, `descripcion`, `precio`, `imagen`) VALUES
(52, 'Celulares', '2023-11-30', 'Celular Motorola G23 128GB Azul', 15, 'El Motorola G23 tiene un diseño moderno y ultra delgado, con bordes delgados e increíbles detalles, además de una pantalla HD+ de 6.5\" 90 Hz. Por otro lado, vas a disfrutar de parlantes estéreo con Audio Dolby Atmos con los que vas a vivir una experiencia de sonido multidimensional que te permite sentir mejor los bajos, descubrir voces más nítidas y escuchar con mayor claridad. Cuenta con un sistema de cámaras de 50 MP, Ultra Gran Angular y Macrol. Además, vas a poder capturar fotos nítidas en condiciones de poca luz, increíbles retratos y acercamientos detallados. Vas a dejar de preocuparte por quedarte sin batería ya que el G23 tiene una batería de 5,000 mAh y un cargador TurboPower 30W. Cuenta con un procesador MediaTek Helio G85 que ofrece un  desempeño más rápido que los moto g de la generación anterior.', 180000.00, 'productos/164200-800-auto.png');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuarios`
--

CREATE TABLE `usuarios` (
  `id` int(10) NOT NULL,
  `nombre` varchar(20) NOT NULL,
  `apellido` varchar(30) NOT NULL,
  `dni` int(11) NOT NULL,
  `usuario` varchar(255) NOT NULL,
  `clave` varchar(255) NOT NULL,
  `email` varchar(100) NOT NULL,
  `telefono` int(10) NOT NULL,
  `tipo` varchar(10) NOT NULL DEFAULT 'user'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

--
-- Volcado de datos para la tabla `usuarios`
--

INSERT INTO `usuarios` (`id`, `nombre`, `apellido`, `dni`, `usuario`, `clave`, `email`, `telefono`, `tipo`) VALUES
(1, 'Andrea', 'Mirabal', 55900876, 'administrador', '123456', 'esther.mirabal.1402@gmail.com', 2147453647, 'admin'),
(2, 'Santiago', 'Gomez', 88990675, 'santiago', '123456', 'esther.mirabal.1402@gmail.com', 2147483647, 'admin'),
(3, 'Esther Andrea', 'Mirabal', 96000000, 'esther', '123456', 'esther.mirabal.1402@gmail.com', 2147483646, 'user'),
(4, 'Simon', 'Gomez', 342567654, 'simongs', '123456', 'simongs89@gmail.com', 2147483647, 'user'),
(5, 'lucas', 'fernandez', 39494541, 'lucass', '123456', 'lucasfer@gmail.com', 2147483647, 'user');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `venta`
--

CREATE TABLE `venta` (
  `id` int(11) NOT NULL,
  `fecha` date DEFAULT NULL,
  `usuario_id` int(11) DEFAULT NULL,
  `subtotal` decimal(11,2) NOT NULL,
  `iva` decimal(11,2) NOT NULL,
  `total` decimal(11,2) NOT NULL,
  `ticket` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

--
-- Volcado de datos para la tabla `venta`
--

INSERT INTO `venta` (`id`, `fecha`, `usuario_id`, `subtotal`, `iva`, `total`, `ticket`) VALUES
(1, '2023-11-29', 3, 122999.00, 25829.79, 148828.79, 'Tickets/Ticket28112023091145.pdf'),
(2, '2023-11-30', 3, 122999.00, 25829.79, 148828.79, 'Tickets/Ticket30112023101133.pdf');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `itemventa`
--
ALTER TABLE `itemventa`
  ADD PRIMARY KEY (`id`),
  ADD KEY `venta_id` (`venta_id`);

--
-- Indices de la tabla `productos`
--
ALTER TABLE `productos`
  ADD PRIMARY KEY (`codigo`);

--
-- Indices de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  ADD PRIMARY KEY (`id`),
  ADD KEY `email` (`email`),
  ADD KEY `email_2` (`email`);

--
-- Indices de la tabla `venta`
--
ALTER TABLE `venta`
  ADD PRIMARY KEY (`id`),
  ADD KEY `usuario_id` (`usuario_id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `itemventa`
--
ALTER TABLE `itemventa`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT de la tabla `productos`
--
ALTER TABLE `productos`
  MODIFY `codigo` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;

--
-- AUTO_INCREMENT de la tabla `usuarios`
--
ALTER TABLE `usuarios`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT de la tabla `venta`
--
ALTER TABLE `venta`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `itemventa`
--
ALTER TABLE `itemventa`
  ADD CONSTRAINT `itemventa_ibfk_1` FOREIGN KEY (`venta_id`) REFERENCES `venta` (`id`);

--
-- Filtros para la tabla `venta`
--
ALTER TABLE `venta`
  ADD CONSTRAINT `venta_ibfk_1` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
